### ISSUE TITLE
add maps components

### ISSUE THREAD

**Issue by dwhitacre** [dwhitacre/hds-tm-events#32]
- add to the weekly page the maps for the week alongside the results
- add qualifying maps as well
- need to add maps to weeklies and matches for this in db and api
- should create cache table from tmio for campaign like we do for player data

**Comment by HD-Enlightenment** [comment]
This was going to be my next suggestion

**Comment by dwhitacre** [comment]
added maps, weeklymaps

next add some ui for this

**Comment by dwhitacre** [comment]
the pieces are almost complete, not sure how i want it to display
