### ISSUE TITLE
Make a weekly page for the upcoming week

### ISSUE THREAD

**Issue by HD-Enlightenment** [dwhitacre/hds-tm-events#38]
Have a page for the upcoming week displaying the maps that will be played? The page can be replaced with the current results format when competition starts

**Comment by dwhitacre** [comment]
do you want this to be different than the existing weekly page? i can create the weekly without any data preemptively
![image](https://github.com/dwhitacre/hds-tm-events/assets/13386624/516e6752-bf43-40bb-86f0-1526e2d01c07)
![image](https://github.com/dwhitacre/hds-tm-events/assets/13386624/ed92c485-9f25-4bdc-8fd2-13e83b4c6ddc)

**Comment by HD-Enlightenment** [comment]
the only thing i would want to be different would maps displaying at the top since everything else is blank, its the information that is needed more
